### ISSUE TITLE
 About component usage

### ISSUE THREAD

**Issue by ZhQuella** [yoonasy/vue3-virtual-scroller#1]
hi~
I used the vue3-virtual-scroller component in the project
code show as below

```
<template>
  <div class="home-index-full home-index-head">
    <DynamicScroller
      class="scroller"
      :items="resetMenuList"
      key-field="name"
      :min-item-size="80"
    >
      <template #default="{ item, index, active }">
        <DynamicScrollerItem
          :item="item"
          :active="active"
          :size-dependencies="[
            item.message,
          ]"
          :data-index="index"
        >
          <menu-warp :base-data="item" />
        </DynamicScrollerItem>
      </template>
    </DynamicScroller>
  </div>
</template>
```

You can see the elements normally，However, no virtual scrolling effect is seen！

**Comment by ppvy** [comment]
hi, 
There is currently no time to maintain the project
You can use the original author's supporting Vue3 component
[vue-virtual-scroller@next](https://github.com/Akryum/vue-virtual-scroller/tree/next/packages/vue-virtual-scroller).
